### ISSUE TITLE
SetDeviceIndex should not be called on a SteamVR_TrackedController

### ISSUE THREAD

**Issue by zbarryte** [MakeSchool-Tutorials/Drift-Unity-VR#1]
This should not be called, because the device index is non-deterministic, and, though 1 may work in some cases, won't work in all.  The index changes based on device assignment of the system.

SteamVR_TrackedController should automatically get its device index from SteamVR_TrackedObject, which should be attached to the object already.  This may require a set-up like the [Camera Rig] prefab, with a manager on the root object setting the indices of the SteamVR_TrackedObjects.

The other option is to cover all bases and use LeftMost and RightMost so that players can use either controller.

**Comment by dionlarson** [comment]
Ended up using `Rightmost` and making it a challenge for students to implement `Leftmost`.
