### ISSUE TITLE
2. Creating The Player

### ISSUE THREAD

**Issue by donnakashima** [MakeSchool-Tutorials/Drift-Unity-VR#4]
For the first "Show solution", instructions were very ambiguous. Did not state that we were going to be editing the code inside the "Steam VR_Tracked Object" script, the only way user would find out is by looking at the picture after expanding "Show solution" at the end of the section*.

**Comment by dionlarson** [comment]
Sorry about that, a rendering bug allowed part of that to sneak back in. That section does not harm you but is not necessary to complete and has been fully removed.
